# Generated by Django 5.2.1 on 2025-05-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttransactionhistory',
            name='transaction_type',
            field=models.CharField(max_length=100),
        ),
    ]
