# Generated by Django 5.2.1 on 2025-05-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchantbalance')),
            ],
            options={
                'verbose_name': 'Merchant Transaction History',
                'verbose_name_plural': 'Merchant Transaction Histories',
                'db_table': 'merchant_transaction_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
