# Generated by Django 5.2.1 on 2025-05-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_merchanttransactionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchanttransactionhistory',
            old_name='consumer',
            new_name='merchant',
        ),
    ]
